---
title: "README"
author: "Michael Culshaw-Maurer"
date: "`r format(Sys.time(), '%I:%M%p %B %d, %Y')`"
output: 
  md_document:
    variant: gfm
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F,
  fig.path = "README_files/figure-gfm/README-")

source("src/data_scraping_functions.R")
library(ggplot2)

theme_set(theme_minimal())
```

# NBA Data Analysis and Visualization

Doing some analysis and visualization of NBA data, for fun.

Data, so far, are gathered from the wonderful [Basketball Reference](https://www.basketball-reference.com/).

## Data as of `r as.POSIXct(Sys.time()) %>% `attr<-`("tzone", "CST") %>% format("%I:%M%p %B %d, %Y")`

### Team Standings

```{r, message=F}
td <- get_team_data(ratings = T)

standings <- td %>% 
  select(team, g, conf, div, w, l, w_l_percent, 
         unadjusted_n_rtg) %>% 
  group_by(conf) %>% 
  arrange(desc(w_l_percent), desc(unadjusted_n_rtg)) %>% 
  group_split(.keep = F)

col_labels <- c("Team", "Games", "Div.", "W", "L",
                "W/L", "Net Rating")
```

#### Eastern Conference

```{r}
standings %>%
  pluck(1) %>% 
  knitr::kable(col.names = col_labels)
```

#### Western Conference

```{r}
standings %>%
  pluck(2) %>% 
  knitr::kable(col.names = col_labels)
```


### Individual Stats

```{r}
d <- get_player_data(advanced = T)
```

#### PPG Leaders

```{r}
d %>% 
  select(player, tm, pts, g) %>% 
  mutate(ppg = pts/g) %>% 
  arrange(desc(ppg)) %>% 
  head(5) %>% 
  knitr::kable()
```

#### VORP Leaders

```{r}
d %>% 
  select(player, tm, vorp) %>% 
  arrange(desc(vorp)) %>% 
  head(5) %>% 
  knitr::kable()
```

```{r}
d %>% 
  slice_max(mp, prop = 0.8) %>% 
  select(player, pos_simple, pts, ast, trb, blk, tov, e_fg_percent, ws_48, vorp) %>% 
  rename(`eFG%` = e_fg_percent, AST = ast, BLK = blk, PTS = pts,
         TOV = tov, TRB = trb, VORP = vorp, `WS/48` = ws_48) %>% 
  mutate(across(where(is.numeric), scales::rescale)) %>% 
  arrange(desc(VORP)) %>% 
  group_by(pos_simple) %>% 
  slice_max(VORP, n = 5) %>% 
  pivot_longer(-(1:2), names_to = "metric") %>% 
  ggplot(aes(x = metric, y = tidytext::reorder_within(player, value, pos_simple), fill = value)) +
  geom_tile() +
  tidytext::scale_y_reordered() +
  facet_wrap(vars(pos_simple), ncol = 1, scales = "free") +
  scale_fill_viridis_c() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Stat",
       y = "Player",
       fill = "Percentile\nin NBA")
```

